export enum ROUTES {
  home = 'home',
  login = 'login',
  welcome = 'welcome',
  myProfile = 'myProfile',
  myPost = 'myPost',
  verify = 'verify',
  favorite = 'favorite',
  addFeed = 'addFeed',
  addFeedPost = 'addFeedPost',
  verifySuccess = 'verifySuccess',
  resetPassword = 'resetPassword',
  registration = 'registration',
  newPassword = 'newPassword',
  bottomTabs = 'bottomTabs',
  mainNavigator = 'mainNavigator',
  influencer = 'influencer',
  bookingSeating = 'bookingSeating',
  bookingTicket = 'bookingTicket',
  bookingCustomer = 'bookingCustomer',
  bookingPayment = 'bookingPayment',
  bookingPaymentWebView = 'bookingPaymentWebView',
  bookingConfirmed = 'bookingConfirmed',
  feed = 'feed',
  chat = 'chat',
  socialAuth = 'socialAuth',

  galleriesNavigator = 'galleriesNavigator',
  gallery = 'gallery',
  galleries = 'galleries',

  attractionsNavigator = 'attractionsNavigator',
  attractions = 'attractions',
  attractionsAll = 'attractionsAll',
  attraction = 'attraction',

  eventsNavigator = 'eventsNavigator',
  events = 'events',
  eventsAll = 'eventsAll',
  event = 'event',

  venuesNavigator = 'venuesNavigator',
  venues = 'venues',
  venuesAll = 'venuesAll',
  venue = 'venue',

  articleNavigator = 'articleNavigator',
  article = 'article',
  articles = 'articles',

  profileNavigator = 'profileNavigator',
  personalInfromation = 'personalInfromation',
  contactPreferences = 'contactPreferences',
  myOrders = 'myOrders',
  myPayments = 'myPayments',
  myReservations = 'myReservations',
  profile = 'profile',

  offersNavigator = 'offersNavigator',
  offers = 'offers',
  offer = 'offer',

  settings = 'settings',
  interests = 'interests',
}
